curl -X POST http://localhost:8080/staff/register \
-H "Content-Type: application/json" \
-d '{
    "name": "sachin",
    "role":"admin",
    "email": "sachinkheradiya015@gmail.com",
    "password": "Sachin@123"
}'

###
curl -X POST http://localhost:8080/staff/register \
-H "Content-Type: application/json" \
-d '{
    "name": "sachin",
    "role":"teacher",
    "email": "sachinkheradiya01@gmail.com",
    "password": "Sachin@123"
}'

###
curl -X POST http://localhost:8080/staff/login \
-H "Content-Type: application/json" \
-d '{
    "email": "sachinkheradiya01@gmail.com",
   "password": "Sachin@123"
}'

###
curl -X POST http://localhost:8080/staff/login \
-H "Content-Type: application/json" \
-d '{
    
    "email": "sachinkheradiya015@gmail.com",
    "password": "Sachin@123"
}'

//teachers 
###
curl -X POST http://localhost:8080/teacher/register \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjI1NzMwMDRmNGZlODg3MTdjNDllZSIsImlhdCI6MTczOTc0MjQ0NCwiZXhwIjoxNzM5NzQyNDg5fQ.clF1TNmgZj7miEMkYXaUtT33J23hg2-WOouXYWG-Uvc" \
-d '{
    "name": "kishan",
    "gender": "Male",
    "address": {
        "street": "123 Main St",
        "city": "New York",
        "state": "Gujarat"
    },
    "classes": [6, 7, 8]
}'

###
curl -X PUT http://localhost:8080/teacher/update/67b17ff6a545385a80cf6547 \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjE1YzA2ZTYwMjgyM2QwNzI2MDIwNSIsImlhdCI6MTczOTY4NjAxOSwiZXhwIjoxNzM5Njg2OTE5fQ.QS_nkIITemIGjszVPMFM6zg0gN-SP3dOa5mnil0AcAs" \
-d '{
    "name": "sachin",
    "gender": "Male",
    "address": {
        "street": "123 Main St",
        "city": "New York",
        "state": "NY"
    },
    "classes": [1, 2, 3]
}'

###
curl -X GET http://localhost:8080/teacher/get/67b182839d57192497ebe369 \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjE1YzA2ZTYwMjgyM2QwNzI2MDIwNSIsImlhdCI6MTczOTY4NjAxOSwiZXhwIjoxNzM5Njg2OTE5fQ.QS_nkIITemIGjszVPMFM6zg0gN-SP3dOa5mnil0AcAs"
###

curl -X GET http://localhost:8080/teacher/getall \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjE1YzA2ZTYwMjgyM2QwNzI2MDIwNSIsImlhdCI6MTczOTY4NzA0MiwiZXhwIjoxNzM5Njg3OTQyfQ.89hp-argWQtH3MxyQtcsvNYqemxanOYvgFaHJ0yyDk4"
###

curl -X DELETE http://localhost:8080/teacher/delete/67b17ff6a545385a80cf6547 \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjE1YzA2ZTYwMjgyM2QwNzI2MDIwNSIsImlhdCI6MTczOTY4NjAxOSwiZXhwIjoxNzM5Njg2OTE5fQ.QS_nkIITemIGjszVPMFM6zg0gN-SP3dOa5mnil0AcAs"
###

//student
curl -X POST http://localhost:8080/student/register \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjE1YzA2ZTYwMjgyM2QwNzI2MDIwNSIsImlhdCI6MTczOTY4ODc5NiwiZXhwIjoxNzM5Njg5Njk2fQ.KeY0C3NKzVVHpIMha1Tgo_J6iXmG9M5rvCpm6N8v1ks" \
-d '{
    "name": "Dev",
    "fatherName": "Father",
    "motherName": "Mother",
    "contactNo": "9016411168",
    "DOB": "15/05/1000",
    "address": {
        "street": "123 Main St",
        "city": "New York",
        "state": "gujarat"
    },
    "gender": "Male",
    "class": 6
}'
###

curl -X PUT  http://localhost:8080/student/update/67b188750e8df017679634a4 \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjE1YzA2ZTYwMjgyM2QwNzI2MDIwNSIsImlhdCI6MTczOTY4Nzg3MywiZXhwIjoxNzM5Njg4NzczfQ.LdnjtuGaZ5-VfXdWc6UerCz6OdY3k3qRG-OLRjC66Vw" \
-d '{
    "name": "Student",
    "fatherName": "Father",
    "motherName": "Mother Name",
    "contactNo": "1234567890",
    "DOB": "2005-01-15",
    "address": {
        "street": "123 Main St",
        "city": "New York",
        "state": "NY"
    },
    "gender": "Male",
    "class": 6
}'

###
curl -X GET http://localhost:8080/student/get/67b188750e8df017679634a4 \
-H "Content-Type: application/json"
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjE1YzA2ZTYwMjgyM2QwNzI2MDIwNSIsImlhdCI6MTczOTY4Nzg3MywiZXhwIjoxNzM5Njg4NzczfQ.LdnjtuGaZ5-VfXdWc6UerCz6OdY3k3qRG-OLRjC66Vw" \

###
curl -X GET http://localhost:8080/student/getall \
-H "Content-Type: application/json"
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjE1YzA2ZTYwMjgyM2QwNzI2MDIwNSIsImlhdCI6MTczOTY4Nzg3MywiZXhwIjoxNzM5Njg4NzczfQ.LdnjtuGaZ5-VfXdWc6UerCz6OdY3k3qRG-OLRjC66Vw" \
###
curl -X DELETE http://localhost:8080/student/delete/67b188750e8df017679634a4 \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjE1YzA2ZTYwMjgyM2QwNzI2MDIwNSIsImlhdCI6MTczOTY4Nzg3MywiZXhwIjoxNzM5Njg4NzczfQ.LdnjtuGaZ5-VfXdWc6UerCz6OdY3k3qRG-OLRjC66Vw" \


###
curl -X PUT "http://localhost:8080/student/update/67b18b7f0daded01d525159d" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjE4NTExOGYyZDZiOGYyMzk4YjRkNCIsImlhdCI6MTczOTY4ODg3NCwiZXhwIjoxNzM5Njg5Nzc0fQ.3UtqJKSJ2weQ8yfGxPWOIICwYWdnIi5mPMhmZcYFX0w" \
-d '{
    "name": "Student",
    "fatherName": "Father",
    "motherName": "Mother Name",
    "contactNo": "1234567890",
    "DOB": "2005-01-15",
    "address": {
        "street": "123 Main St",
        "city": "New York",
        "state": "NY"
    },
    "gender": "Male",
    "class": 6
}'

###
curl -X POST http://localhost:8080/staff/refresh_token \
     -H "Content-Type: application/json" \
     -d '{"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjI1NzMwMDRmNGZlODg3MTdjNDllZSIsImlhdCI6MTczOTc0MjIzOSwiZXhwIjoxNzQyMzM0MjM5fQ.nmZK8ZsKi25GCUI8Sn7Bxl7LUxd-SUwRV4H1vanMujo"}'


